version: '3.8'
services:
  database: 
    image: postgres:13.2
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user
      POSTGRES_DB: chatapp
    expose:
        - '5432'
    volumes:
        - db-data:/var/lib/postgresql/data

volumes:
    db-data: {}
