version: '3.8'
services:
  website:
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - POSTGRES_URI=postgres://user:postgres123@database:5432/chatapp
    build: .
    ports:
      - 8000:3000
    depends_on:
      - database
    restart: always
  database:
    image: postgres:13.8
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_USER=user
      - POSTGRES_DB=chatapp
    expose:
      - '5432'
    ports:
      - '5434:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
